# Sanitized wired 802.1X authenticator example
interface=enp0s8
driver=wired

ieee8021x=1
eapol_version=2

auth_server_addr=192.168.10.112
auth_server_port=1812
auth_server_shared_secret=CHANGE_ME

acct_server_addr=192.168.10.112
acct_server_port=1813
acct_server_shared_secret=CHANGE_ME
